### ISSUE TITLE
Our "@slack_" reserved mxid prefix conflicts with matrix-appservice-slack's, causing the bridge to be unable to create Matrix ghost users if matrix-appservice-slack is also running

### ISSUE THREAD

**Issue by jeffcasavant** [matrix-hacks/matrix-puppet-slack#34]
When the bridge has to create a new Slack user on the Matrix side (sometimes it doesn't in my deployment since it picks the same usernames as matrix-appservice-slack), I get this error:

```
Error in handleThirdPartyRoomMessage { [M_UNKNOWN: No row found]
  errcode: 'M_UNKNOWN',
  name: 'M_UNKNOWN',
  message: 'No row found',
  data: { errcode: 'M_UNKNOWN', error: 'No row found' },
  httpStatus: 404 } { roomId: '<removed>',
  senderId: '<removed>',
  senderName: '<removed>',
  avatarUrl: 'https://avatars.slack-edge.com/<removed>',
  text: '<removed>',
  html: '
removed
' } ﻿
```

**Comment by thomas-profitt** [comment]
To add more info to this bug:

I experience it too, on 1aa002c

It happens when the bridge sees a message from a Slack user for the first time and must create a Matrix ghost user for them.

When the bridge sees subsequent messages from that user, the ghost user will already have been created, and everything will work normally from then on.

I expect this issue will be one of the easier ones to fix.

**Comment by jeffcasavant** [comment]
In my experience I get this continually, it fails to create the ghost user altogether.

`[-] POST https://my.matrix.server/_matrix/client/r0/register (AS) HTTP 400 Error: {"errcode":"M_EXCLUSIVE","error":"This user ID is reserved by an application service."} `

I'm also running matrix-appservice-slack for some rooms, so that's clearly what's causing (this part of my) issue.  Is there a way we can change out the user prefix?

**Comment by kfatehi** [comment]
There is. IIRC It’s in the FAQ on the readme of the matrix-puppet-bridge
project.

**Comment by jeffcasavant** [comment]
As far as I can tell, for this bridge you'd need to change it in a few places:

```
diff --git a/app.js b/app.js
index 86add47..8dc633b 100644
--- a/app.js
+++ b/app.js
@@ -12,7 +12,7 @@ class App extends MatrixPuppetBridgeBase {
   setSlackTeam(teamName, userAccessToken) {
     this.teamName = teamName;
     this.userAccessToken = userAccessToken;
-    this.slackPrefix = 'slack';
+    this.slackPrefix = 'slackpuppet';
     this.servicePrefix = `${this.slackPrefix}_${this.teamName}`;
   }
   getServiceName() {
diff --git a/index.js b/index.js
index beb71a8..ce85b73 100644
--- a/index.js
+++ b/index.js
@@ -23,7 +23,7 @@ new Cli({
       reg.setHomeserverToken(AppServiceRegistration.generateToken());
       reg.setAppServiceToken(AppServiceRegistration.generateToken());
       reg.setSenderLocalpart(`slack_bot`);
-      reg.addRegexPattern("users", `@slack_.*`, true);
+      reg.addRegexPattern("users", `@slackpuppet_.*`, true);
       callback(reg);
     }).catch(err=>{
       console.error(err.message);
@@ -81,7 +81,7 @@ new Cli({
           console.log('on alias query');
         },
         thirdPartyLookup: {
-          protocols: config.slack.map(i=>`slack_${i.team_name}`),
+          protocols: config.slack.map(i=>`slackpuppet_${i.team_name}`),
           getProtocol: function() {
             console.log('get proto');
           },
```
however, it seems to be working cleanly now.  I'm going to test it for a few days & see if I have the same quirk Thomas is having.

**Comment by thomas-profitt** [comment]
Since the prefix is ultimately an arbitrary string, and we want to avoid making any assumptions of our own about the user's homeserver and bridges, it'd be nice to make the prefix a configurable parameter that has a sensible default but can be changed during setup.

**Comment by thomas-profitt** [comment]
We may not be able to change it in the codebase without causing problems anyway:

If the old version assumes "@slack_" is the prefix and assumes ghost users will have that prefix, and the new version assumes all ghosts' mxids have a new prefix, we'd have to take on extra complexities to make sure the new version doesn't make assumptions that aren't true (the ultimate cause of every bug ever)

**Comment by jeffcasavant** [comment]
I modified the source of this bridge & it seems to be behaving fine; but now whenever the bot has to create a new Matrix-side _room_ it throws the No Row Found error.

**Comment by thomas-profitt** [comment]
Modifying source to change the prefix will work fine for you because you don't already have @slack_* users on your homeserver. Just be sure you don't change your custom prefix afterward or weird stuff will probably happen.

**Comment by jeffcasavant** [comment]
I can confirm I have the issue when the bridge has to create new ghost users as well, just as you said you were experiencing.
