### ISSUE TITLE
When the first message from a user is received and a ghost user is created, a [M_UNKNOWN: No row found] error is thrown. Subsequent messages work.

### ISSUE THREAD

**Issue by thomas-profitt** [matrix-hacks/matrix-puppet-slack#36]
I experience it too, on #1aa002c

It happens when the bridge sees a message from a Slack user for the first time and must create a Matrix ghost user for them.

The ghost user does get created, but their first message fails to send with this error.

From then on, when the bridge sees subsequent messages from that user, everything will work normally.

I expect this issue will be one of the easier ones to fix.

https://github.com/matrix-hacks/matrix-puppet-bridge/pull/35 may fix this. I have yet to test it.

**Comment by jeffcasavant** [comment]
Deployed twouters/matrix-puppet-bridge#6aa5f88 under my matrix-puppet-slack config.  I'll let you know if it fixes things.

**Comment by jeffcasavant** [comment]
As of now that appears to be working.  I have gotten messages from new people & messages that have spawned new rooms, and I haven't lost the first message in them.

**Comment by thomas-profitt** [comment]
Great!

I'm testing it too, but I've been running the bridge for a while, so it's not every day a user in one of my teams posts for the first time.

Since it fixed the problem for you and hasn't broken anything for me, I'll merge https://github.com/matrix-hacks/matrix-puppet-bridge/pull/35, bump bridge's version number, and require that version of bridge in matrix-puppet-slack master so we can close this issue.
