### ISSUE TITLE
Login with email/password instead of legacy api token?

### ISSUE THREAD

**Issue by Pneumaticat** [matrix-hacks/matrix-puppet-slack#43]
It looks like I often have to request legacy API tokens from Slack workspace admins, which usually deny me (probably for good reason or spam issues).

As such, would it be possible to also support logging in with email and password, or does the Slack API prohibit that?

**Comment by thomas-profitt** [comment]
Yep, Slack doesn't allow logging into the "legacy API" with any other info but that token, and workspace admins have the option to prevent users from generating them.

Proprietary comms services suck.

**Comment by Pneumaticat** [comment]
Welp. Worth a shot. Thanks for the quick response :)
