### ISSUE TITLE
Matrix-to-Slack image uploads (m.image msgtype events) no longer work.

### ISSUE THREAD

**Issue by thomas-profitt** [matrix-hacks/matrix-puppet-slack#54]

**Comment by thomas-profitt** [comment]
I'm reopening this, and updating the title, because, after testing, I found that Matrix-to-Slack m.file events are now bridged properly, but m.image events don't.

I'll create new issues for m.audio and m.video, so we have separate issues for each of these event types.

**Comment by d3m3vilurr** [comment]
@thomas-profitt did you test with last matrix-puppet-bridge? I think that has a bug in upload logic.
please check a my pr matrix-hacks/matrix-puppet-bridge#40

**Comment by thomas-profitt** [comment]
I've merged the PR into a new release (1.16.2), and ran my local matrix-puppet-slack with that version as its matrix-puppet-bridge dependency, but the behavior seen after posting an image via Matrix hasn't changed:

![screenshot from 2018-12-18 19-41-05](https://user-images.githubusercontent.com/13843293/50193932-9be06a00-0330-11e9-9efe-9c767edb59f4.png)

**Comment by d3m3vilurr** [comment]
weird... i have tested this with slack and hangout bridge, and both are work image bridge from matrix.

well....
https://github.com/matrix-hacks/matrix-puppet-slack/blob/master/client.js#L210
i think it could be synapse configure problem.
slack required be accessible image url from slack side. so if matrix server can't serve image to unauthorized user, probably it wouldn't work.
can you check this?
