### ISSUE TITLE
Failed to register AS

### ISSUE THREAD

**Issue by pztrn** [matrix-hacks/matrix-puppet-slack#83]
After following guide from README.md I get:

```
chat node[21376]: { [M_EXCLUSIVE: This application service has not reserved this kind of alias.]
chat node[21376]:   name: 'M_EXCLUSIVE',
chat node[21376]:   message:
chat node[21376]:    'This application service has not reserved this kind of alias.',
chat node[21376]:   data:
chat node[21376]:    { errcode: 'M_EXCLUSIVE',
chat node[21376]:      error:
chat node[21376]:       'This application service has not reserved this kind of alias.' },
chat node[21376]:   httpStatus: 400 }
```

**Comment by thomas-profitt** [comment]
As I understand it, this error is sent by the homeserver when the bridge tries to create a room alias that begins with a prefix, or matches a regex, that hasn't been reserved in the registration.yaml file for the appservice.

- Update matrix-puppet-slack to current master
- npm install to pull the latest dependencies, particularly matrix-puppet-bridge
- regenerate your slack-registration.yaml
- Install the new slack-registration.yaml in Synapse's data directory
- Be sure that, in Synapse's homeserver.yaml, it's `app_service_config_files` key, the value of which is an array, includes the root-relative path to that slack-registration.yaml file
- Restart synapse
- Start matrix-puppet-slack again

**Comment by pztrn** [comment]
Actually I've solved that with that patch:

```
diff --git a/index.js b/index.js
index 450881f..ba781ff 100644
--- a/index.js
+++ b/index.js
@@ -24,7 +24,7 @@ new Cli({
       reg.setAppServiceToken(AppServiceRegistration.generateToken());
       reg.setSenderLocalpart(`slack_bot`);
       reg.addRegexPattern("users", `@slack_.*`, true);
-      reg.addRegexPattern("aliases", `@slack_.*`, false);
+      reg.addRegexPattern("aliases", `#slack_.*`, false);
       callback(reg);
     }).catch(err=>{
       console.error(err.message);
```

Found somewhere around here, by the way.

**Comment by thomas-profitt** [comment]
Oh, good! That change is part of [1.12.0](https://github.com/matrix-hacks/matrix-puppet-slack/releases/tag/1.12.0), so it sounds like we can close this. Thanks for filing the issue!
